name: push

on:
  push:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: 🧪 Test
        run: npm test
      - run: npm install -g npm@latest
      - name: 📢 Release
        uses: tobua/release-npm-action@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
